# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MDI_Tourism.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 401, 351))
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow_sportsEvent = QtWidgets.QWidget()
        self.subwindow_sportsEvent.setObjectName("subwindow_sportsEvent")
        self.lineEdit_venue = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEdit_venue.setGeometry(QtCore.QRect(140, 60, 201, 20))
        self.lineEdit_venue.setObjectName("lineEdit_venue")
        self.lineEdit_Title = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEdit_Title.setGeometry(QtCore.QRect(140, 100, 201, 20))
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.lineEdit_Date = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEdit_Date.setGeometry(QtCore.QRect(140, 140, 201, 20))
        self.lineEdit_Date.setObjectName("lineEdit_Date")
        self.lineEditStartTime = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEditStartTime.setGeometry(QtCore.QRect(140, 180, 201, 20))
        self.lineEditStartTime.setObjectName("lineEditStartTime")
        self.lineEdit_EndTime = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEdit_EndTime.setGeometry(QtCore.QRect(140, 220, 201, 20))
        self.lineEdit_EndTime.setObjectName("lineEdit_EndTime")
        self.label_venue = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.label_venue.setGeometry(QtCore.QRect(60, 60, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_venue.setFont(font)
        self.label_venue.setObjectName("label_venue")
        self.labelTitle = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.labelTitle.setGeometry(QtCore.QRect(60, 100, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelDate = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.labelDate.setGeometry(QtCore.QRect(60, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.labelStartTime = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.labelStartTime.setGeometry(QtCore.QRect(60, 180, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setBold(True)
        font.setWeight(75)
        self.labelStartTime.setFont(font)
        self.labelStartTime.setObjectName("labelStartTime")
        self.label_EndTime = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.label_EndTime.setGeometry(QtCore.QRect(60, 220, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_EndTime.setFont(font)
        self.label_EndTime.setObjectName("label_EndTime")
        self.labelTitle_sportsEvent = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.labelTitle_sportsEvent.setGeometry(QtCore.QRect(70, 10, 231, 31))
        self.labelTitle_sportsEvent.setObjectName("labelTitle_sportsEvent")
        self.labelNumGuest = QtWidgets.QLabel(self.subwindow_sportsEvent)
        self.labelNumGuest.setGeometry(QtCore.QRect(20, 260, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setBold(True)
        font.setWeight(75)
        self.labelNumGuest.setFont(font)
        self.labelNumGuest.setObjectName("labelNumGuest")
        self.lineEdit_NumGuest = QtWidgets.QLineEdit(self.subwindow_sportsEvent)
        self.lineEdit_NumGuest.setGeometry(QtCore.QRect(140, 260, 201, 20))
        self.lineEdit_NumGuest.setObjectName("lineEdit_NumGuest")
        self.pushButtonSaveEvent = QtWidgets.QPushButton(self.subwindow_sportsEvent)
        self.pushButtonSaveEvent.setGeometry(QtCore.QRect(230, 290, 111, 23))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSaveEvent.setFont(font)
        self.pushButtonSaveEvent.setObjectName("pushButtonSaveEvent")
        self.mdiArea_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_2.setGeometry(QtCore.QRect(400, 0, 441, 311))
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.subwindowVenueList = QtWidgets.QWidget()
        self.subwindowVenueList.setObjectName("subwindowVenueList")
        self.labelVenuTitle = QtWidgets.QLabel(self.subwindowVenueList)
        self.labelVenuTitle.setGeometry(QtCore.QRect(130, 5, 151, 31))
        self.labelVenuTitle.setObjectName("labelVenuTitle")
        self.pushButtonReloadVenue = QtWidgets.QPushButton(self.subwindowVenueList)
        self.pushButtonReloadVenue.setGeometry(QtCore.QRect(264, 250, 111, 23))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonReloadVenue.setFont(font)
        self.pushButtonReloadVenue.setObjectName("pushButtonReloadVenue")
        self.listWidgetVenueList = QtWidgets.QListWidget(self.subwindowVenueList)
        self.listWidgetVenueList.setGeometry(QtCore.QRect(15, 40, 351, 192))
        self.listWidgetVenueList.setObjectName("listWidgetVenueList")
        self.mdiArea_4 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_4.setGeometry(QtCore.QRect(400, 310, 441, 311))
        self.mdiArea_4.setObjectName("mdiArea_4")
        self.subwindow_SportsVenue = QtWidgets.QWidget()
        self.subwindow_SportsVenue.setObjectName("subwindow_SportsVenue")
        self.labelTitle_sportsVenue = QtWidgets.QLabel(self.subwindow_SportsVenue)
        self.labelTitle_sportsVenue.setGeometry(QtCore.QRect(70, 10, 231, 31))
        self.labelTitle_sportsVenue.setObjectName("labelTitle_sportsVenue")
        self.lineEditVName = QtWidgets.QLineEdit(self.subwindow_SportsVenue)
        self.lineEditVName.setGeometry(QtCore.QRect(100, 60, 271, 20))
        self.lineEditVName.setObjectName("lineEditVName")
        self.lineEdit_Address = QtWidgets.QLineEdit(self.subwindow_SportsVenue)
        self.lineEdit_Address.setGeometry(QtCore.QRect(100, 100, 271, 20))
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.lineEdit_Capacity = QtWidgets.QLineEdit(self.subwindow_SportsVenue)
        self.lineEdit_Capacity.setGeometry(QtCore.QRect(100, 140, 271, 20))
        self.lineEdit_Capacity.setObjectName("lineEdit_Capacity")
        self.labelVName = QtWidgets.QLabel(self.subwindow_SportsVenue)
        self.labelVName.setGeometry(QtCore.QRect(10, 60, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelVName.setFont(font)
        self.labelVName.setObjectName("labelVName")
        self.label_VenueAddress = QtWidgets.QLabel(self.subwindow_SportsVenue)
        self.label_VenueAddress.setGeometry(QtCore.QRect(10, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_VenueAddress.setFont(font)
        self.label_VenueAddress.setObjectName("label_VenueAddress")
        self.label_Capacity = QtWidgets.QLabel(self.subwindow_SportsVenue)
        self.label_Capacity.setGeometry(QtCore.QRect(10, 140, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Capacity.setFont(font)
        self.label_Capacity.setObjectName("label_Capacity")
        self.pushButtonSaveVenue = QtWidgets.QPushButton(self.subwindow_SportsVenue)
        self.pushButtonSaveVenue.setGeometry(QtCore.QRect(240, 180, 111, 23))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSaveVenue.setFont(font)
        self.pushButtonSaveVenue.setObjectName("pushButtonSaveVenue")
        self.mdiArea_3 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_3.setGeometry(QtCore.QRect(0, 350, 401, 311))
        self.mdiArea_3.setObjectName("mdiArea_3")
        self.subwindow_EventList = QtWidgets.QWidget()
        self.subwindow_EventList.setObjectName("subwindow_EventList")
        self.labelTitle_2 = QtWidgets.QLabel(self.subwindow_EventList)
        self.labelTitle_2.setGeometry(QtCore.QRect(110, 0, 151, 31))
        self.labelTitle_2.setObjectName("labelTitle_2")
        self.pushButtonReloadEvent = QtWidgets.QPushButton(self.subwindow_EventList)
        self.pushButtonReloadEvent.setGeometry(QtCore.QRect(250, 250, 111, 23))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonReloadEvent.setFont(font)
        self.pushButtonReloadEvent.setObjectName("pushButtonReloadEvent")
        self.listWidgetEventList = QtWidgets.QListWidget(self.subwindow_EventList)
        self.listWidgetEventList.setGeometry(QtCore.QRect(15, 40, 341, 192))
        self.listWidgetEventList.setObjectName("listWidgetEventList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 21))
        self.menubar.setObjectName("menubar")
        self.menuSubWindows = QtWidgets.QMenu(self.menubar)
        self.menuSubWindows.setObjectName("menuSubWindows")
        self.menuData_Maintenance = QtWidgets.QMenu(self.menubar)
        self.menuData_Maintenance.setObjectName("menuData_Maintenance")
        self.menuOlympic_Events = QtWidgets.QMenu(self.menuData_Maintenance)
        self.menuOlympic_Events.setObjectName("menuOlympic_Events")
        self.menuOlympic_Venues = QtWidgets.QMenu(self.menuData_Maintenance)
        self.menuOlympic_Venues.setObjectName("menuOlympic_Venues")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionArrange_Casscade = QtWidgets.QAction(MainWindow)
        self.actionArrange_Casscade.setObjectName("actionArrange_Casscade")
        self.actionArrange_Tile = QtWidgets.QAction(MainWindow)
        self.actionArrange_Tile.setObjectName("actionArrange_Tile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_New_Event = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Event.setObjectName("actionAdd_New_Event")
        self.actionEdit_Existing_Event = QtWidgets.QAction(MainWindow)
        self.actionEdit_Existing_Event.setObjectName("actionEdit_Existing_Event")
        self.actionDelete_Existing = QtWidgets.QAction(MainWindow)
        self.actionDelete_Existing.setObjectName("actionDelete_Existing")
        self.actionShow_File_ContentEvent = QtWidgets.QAction(MainWindow)
        self.actionShow_File_ContentEvent.setObjectName("actionShow_File_ContentEvent")
        self.actionAdd_New_Venue = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Venue.setObjectName("actionAdd_New_Venue")
        self.actionEdit_Existing_Record = QtWidgets.QAction(MainWindow)
        self.actionEdit_Existing_Record.setObjectName("actionEdit_Existing_Record")
        self.actionDelete_Existing_Record = QtWidgets.QAction(MainWindow)
        self.actionDelete_Existing_Record.setObjectName("actionDelete_Existing_Record")
        self.actionShow_File_Content_Venue = QtWidgets.QAction(MainWindow)
        self.actionShow_File_Content_Venue.setObjectName("actionShow_File_Content_Venue")
        self.menuSubWindows.addAction(self.actionArrange_Casscade)
        self.menuSubWindows.addAction(self.actionArrange_Tile)
        self.menuSubWindows.addSeparator()
        self.menuSubWindows.addAction(self.actionExit)
        self.menuOlympic_Events.addAction(self.actionAdd_New_Event)
        self.menuOlympic_Events.addAction(self.actionEdit_Existing_Event)
        self.menuOlympic_Events.addAction(self.actionDelete_Existing)
        self.menuOlympic_Events.addAction(self.actionShow_File_ContentEvent)
        self.menuOlympic_Venues.addAction(self.actionAdd_New_Venue)
        self.menuOlympic_Venues.addAction(self.actionEdit_Existing_Record)
        self.menuOlympic_Venues.addAction(self.actionDelete_Existing_Record)
        self.menuOlympic_Venues.addAction(self.actionShow_File_Content_Venue)
        self.menuData_Maintenance.addAction(self.menuOlympic_Events.menuAction())
        self.menuData_Maintenance.addAction(self.menuOlympic_Venues.menuAction())
        self.menubar.addAction(self.menuSubWindows.menuAction())
        self.menubar.addAction(self.menuData_Maintenance.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subwindow_sportsEvent.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_venue.setText(_translate("MainWindow", "Event Venue"))
        self.labelTitle.setText(_translate("MainWindow", "Event Title"))
        self.labelDate.setText(_translate("MainWindow", "Event Date"))
        self.labelStartTime.setText(_translate("MainWindow", "Start Time"))
        self.label_EndTime.setText(_translate("MainWindow", "End Time"))
        self.labelTitle_sportsEvent.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#c8002f;\">TOURISM EVENTS</span></p></body></html>"))
        self.labelNumGuest.setText(_translate("MainWindow", "Number of Guests"))
        self.pushButtonSaveEvent.setText(_translate("MainWindow", "SAVE"))
        self.subwindowVenueList.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.labelVenuTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#c80321;\">VENUE LIST</span></p></body></html>"))
        self.pushButtonReloadVenue.setText(_translate("MainWindow", "Reload Events"))
        self.subwindow_SportsVenue.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.labelTitle_sportsVenue.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#c8002f;\">TOURISM VENUE</span></p></body></html>"))
        self.labelVName.setText(_translate("MainWindow", "Venue Name"))
        self.label_VenueAddress.setText(_translate("MainWindow", "Venue Address"))
        self.label_Capacity.setText(_translate("MainWindow", "Capacity"))
        self.pushButtonSaveVenue.setText(_translate("MainWindow", "SAVE"))
        self.subwindow_EventList.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.labelTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#c8020f;\">EVENT LIST</span></p></body></html>"))
        self.pushButtonReloadEvent.setText(_translate("MainWindow", "Reload Events"))
        self.menuSubWindows.setTitle(_translate("MainWindow", "File"))
        self.menuData_Maintenance.setTitle(_translate("MainWindow", "Data Maintenance"))
        self.menuOlympic_Events.setTitle(_translate("MainWindow", "Sports Events"))
        self.menuOlympic_Venues.setTitle(_translate("MainWindow", "Sports Venue"))
        self.menuReport.setTitle(_translate("MainWindow", "Reporting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionArrange_Casscade.setText(_translate("MainWindow", "Arrange Casscade"))
        self.actionArrange_Tile.setText(_translate("MainWindow", "Arrange Tile"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_New_Event.setText(_translate("MainWindow", "Add New Event"))
        self.actionEdit_Existing_Event.setText(_translate("MainWindow", "Edit Existing Event"))
        self.actionDelete_Existing.setText(_translate("MainWindow", "Delete Existing"))
        self.actionShow_File_ContentEvent.setText(_translate("MainWindow", "Show File Content"))
        self.actionAdd_New_Venue.setText(_translate("MainWindow", "Add New Venue"))
        self.actionEdit_Existing_Record.setText(_translate("MainWindow", "Edit Existing Record"))
        self.actionDelete_Existing_Record.setText(_translate("MainWindow", "Delete Existing Record"))
        self.actionShow_File_Content_Venue.setText(_translate("MainWindow", "Show File Content"))

